### ISSUE TITLE
Set logic or algo in handleDice.js

### ISSUE THREAD

**Issue by PisoDev77** [team-f12/pigTheDiceGame#5]
## Set methods in handleDice.js

-[] create dice handling class that can handle dice
-[] create rolling dice method
-[] create saving score method
-[] create initializing score method

## 
 basic logic of pig dice game by making methods
# 참조

**Comment by memore2** [comment]
이거 어디까지 진행했나요?

**Comment by PisoDev77** [comment]
merge 되었는데, 혹시 무엇이 더 진행되야 하나요?

**Comment by memore2** [comment]
확인했습니다!!
